---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: servian-demo
spec:
  provider: aws
  secretObjects:
  - secretName: servian-app-secret
    type: Opaque
    data:
    - objectName: secret-token
      key: SECRET_TOKEN
  parameters:
    objects: |
      - objectName: servian-demo/DbUser
        objectType: secretsmanager
        objectAlias: secret-token
      - objectName: servian-demo/DbPassword
        objectType: secretsmanager
        objectAlias: secret-token
      - objectName: servian-demo/DbName
        objectType: secretsmanager
        objectAlias: secret-token
      - objectName: servian-demo/DbPort
        objectType: secretsmanager
        objectAlias: secret-token
      - objectName: servian-demo/DbHost
        objectType: secretsmanager
        objectAlias: secret-token
      - objectName: servian-demo/ListenHost
        objectType: secretsmanager
        objectAlias: secret-token
      - objectName: servian-demo/ListenPort
        objectType: secretsmanager
        objectAlias: secret-token
